### PR TITLE
exclude internal symfony urls

### LINKED ISSUE #293: Do not run CatchUpSubscriptionEngine for _wdt and _profiler requests
Would it make sense to not run the in these kind of requests for the Profiler UI and requests related to the toolbar?
- When a subscription fails the error blocks requests (and therefore) access to the profiler or requests related to the wdt
- When the subscription catches up, makes it hard to trace the request where this actually happend, as this could happen in a request related to the wdt/profiler (e.g. when we want to look at the profiled data for a caught up run)

I would suggest to not run the catchup engine when detecting either kind of request. Not sure though what the best way would be do so (except matching url prefix, but that seems wonky)

### PR DESCRIPTION
**Pull request by DavidBadura**
* fix #293

### CODE REVIEW

File: tests/Unit/RequestListener/AutoSetupListenerTest.php [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+    }
+
+    public function testSkipExcludedUrl(): void
+    {
+        $subscriptionEngine = $this->createMock(SubscriptionEngine::class);
+        $subscriptionEngine->expects($this->never())->method('subscriptions');
+        $subscriptionEngine->expects($this->never())->method('setup');
+
+        $listener = new AutoSetupListener($subscriptionEngine, null, null, '^/_profiler');
+        $listener->onKernelRequest($this->createRequestEvent('/_profiler/test'));
```
Comment (DanielBadura) [inline tests/Unit/RequestListener/AutoSetupListenerTest.php:38]: I think a test which is running with a request which is *not* excluded but with excluded url condfigured is missing.

**Review by DanielBadura — APPROVED** [review]
With the added testcase I mentioned the mutation should also be covered.
